test:
  stage: test
  script:
    - pip install requirements.txt
    - python -m unittest discover

docker-image:
  stage: deploy
  only:
    - master
  script:
    - 'IMAGE_NAME=docker.web-of-systems.com/lava-ctl'
    - 'docker build 
          --build-arg http_proxy=$http_proxy 
          --build-arg https_proxy=$http_proxy 
          --build-arg user=$LAVA_USER 
          --build-arg token=$LAVA_TOKEN
          --build-arg master_addr=$LAVA_SERVER_ADDR
          --build-arg ftp_user=$LAVA_STORAGE_FTP_USER
          --build-arg ftp_pass=$LAVA_STORAGE_FTP_PASS
          -t $IMAGE_NAME .'
    - if [ "$CI_BUILD_REF_NAME" == "master" ]; then
    -   'docker tag $IMAGE_NAME $IMAGE_NAME:$(cat VERSION)'
    -   'docker push $IMAGE_NAME'
    - else
    -   'version="$(cat VERSION)-$(git rev-parse --short HEAD)"'
    -   'docker tag $IMAGE_NAME $IMAGE_NAME:$version'
    -   'docker push $IMAGE_NAME:$version'
    - fi
  tags:
    - RAW
