---
lava:
  server:
    host: "139.25.40.26"
    port: 2041
    files_prefix: "lava-files"

  publisher:
    port: 2042

  sftp:
    port: 2040

  job:
    device: qemux86
    kernel: "http://wosatf.ct.siemens.com/artifactory/wos-images-snapshot/ses-qemux86-devel-EMBS-P-0.4-r1-92-g3e76cfc/bzImage-qemux86.bin"
    rootfs: "http://wosatf.ct.siemens.com/artifactory/wos-images-snapshot/ses-qemux86-devel-EMBS-P-0.4-r1-92-g3e76cfc/ses-image-devel-qemux86.ext4"
    compressed: false
    timeout: 600 # 10 min
