---
lava:
  server:
    host: "139.25.40.26"
    port: 2041
    files_prefix: "lava-files"

  publisher:
    port: 2042

  sftp:
    port: 2040

  jobs:
    timeout: 600 # 10 min

artifactory:
  auth:
    disable: true

  url: "https://wosatf.ct.siemens.com/artifactory/wos-images-snapshot/"
  image: "ses-qemux86-devel-EMBS-P-0.4-r1-92-g3e76cfc"
  kernel: "bzImage-qemux86.bin"
  rootfs: "ses-image-devel-qemux86.ext4"

